package com.mark.conduyt.entity;


import com.mark.conduyt.enums.ApplicationStatus;
import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

@Entity
@Table(
        name = "applications",
        // Prevent a freelancer from applying to the same job multiple times
        uniqueConstraints = @UniqueConstraint(columnNames = {"job_id", "freelancer_id"})
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Application {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Link to the Job being applied for
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "job_id", nullable = false)
    private Job job;

    // Link to the Freelancer who applied
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "freelancer_id", nullable = false)
    private Freelancer freelancer;

    // The pitch text (can be written by freelancer or auto-generated by AI - Feature 7)
    @Column(columnDefinition = "TEXT", nullable = false)
    private String pitch;

    // Feature 5: Algorithmic Compatibility Score calculated by AI (0.0 to 100.0)
    private Double aiCompatibilityScore;

    // Independent status tracking for the candidate's pitch
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ApplicationStatus status = ApplicationStatus.SUBMITTED;

    @Column(nullable = false, updatable = false)
    private LocalDateTime appliedAt = LocalDateTime.now();
}